on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        sudo apt install -y libcap-dev
        python -m pip install --upgrade pip
        python -m pip install -e .
    - name: Lint with flake8
      run: flake8 src tests
    - name: Test with pytest
      run: pytest --cov-report xml:coverage.xml
    - uses: actions/upload-artifact@v4
      with:
        name: coverage.xml
        path: coverage.xml
